# Generated by Django 4.1.1 on 2023-03-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название актива')),
                ('num', models.IntegerField(verbose_name='Кол-во')),
                ('price', models.IntegerField(null=True, verbose_name='Цена')),
                ('month', models.IntegerField(null=True, verbose_name='Месяц')),
            ],
            options={
                'verbose_name': 'Актив',
                'verbose_name_plural': 'Активы',
            },
        ),
    ]
